# Generated by Django 5.1 on 2024-09-05 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0003_material_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='material.material')),
            ],
        ),
    ]
