# Generated by Django 5.1 on 2024-09-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeowner',
            name='Homeowner_id',
        ),
        migrations.RemoveField(
            model_name='homeowner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='homeowner',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='homeowner',
            name='id',
        ),
        migrations.RemoveField(
            model_name='homeowner',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='homeowner',
            name='password',
        ),
        migrations.RemoveField(
            model_name='homeowner',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='homeowner',
            name='created_at',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homeowner',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='homeowner',
            name='homeowner_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
