# Generated by Django 5.1 on 2024-09-05 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowner', '0002_remove_homeowner_homeowner_id_remove_homeowner_email_and_more'),
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeowner',
            name='myuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='homeowners', to='myuser.myuser'),
            preserve_default=False,
        ),
    ]
