# Generated by Django 5.1 on 2024-09-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='id',
        ),
        migrations.RemoveField(
            model_name='material',
            name='image',
        ),
        migrations.AlterField(
            model_name='material',
            name='material_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
