# Generated by Django 5.1 on 2024-09-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_remove_material_id_remove_material_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
